name: "pydolarvenezuela-api"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app-network
    # volumes: # Uncomment this line to use local files
    #   - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network
      
  db:
    image: "postgres:16-alpine3.20"
    restart: always
    container_name: db
    hostname: db
    ports:
      - "${SQL_PORT}:5432"
    environment:
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
      POSTGRES_DB: ${SQL_DB_NAME}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    healthcheck:
      test: pg_isready -d ${SQL_DB_NAME} -U ${SQL_USER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
