services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app-network
    volumes:
      - .:/app
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network
  db:
    image: "postgres:alpine"
    container_name: db
    hostname: db
    ports:
      - "${SQL_PORT}:5432"
    environment:
      POSTGRES_DB: ${SQL_DB_NAME}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
